version: '3.8'
services:
  app:
    image: thenightmaremabbitt/reading-tracker:latest
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo:27017/devdb # Local MongoDB instance
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: local-user
      MONGO_INITDB_ROOT_PASSWORD: local-password
