version: '3.8'
services:
  app:
    image: thenightmaremabbitt/reading-tracker:latest
    environment:
      - NODE_ENV=production
      - MONGO_URL=${MONGO_URL} # Passed dynamically via Jenkins
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME} # Passed dynamically via Jenkins
      MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD} # Passed dynamically via Jenkins
